// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: order.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewRequestOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderRequest  string                 `protobuf:"bytes,1,opt,name=orderRequest,proto3" json:"orderRequest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewRequestOrder) Reset() {
	*x = NewRequestOrder{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewRequestOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRequestOrder) ProtoMessage() {}

func (x *NewRequestOrder) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRequestOrder.ProtoReflect.Descriptor instead.
func (*NewRequestOrder) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *NewRequestOrder) GetOrderRequest() string {
	if x != nil {
		return x.OrderRequest
	}
	return ""
}

type NewResponseOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderResponse string                 `protobuf:"bytes,2,opt,name=orderResponse,proto3" json:"orderResponse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewResponseOrder) Reset() {
	*x = NewResponseOrder{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewResponseOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewResponseOrder) ProtoMessage() {}

func (x *NewResponseOrder) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewResponseOrder.ProtoReflect.Descriptor instead.
func (*NewResponseOrder) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *NewResponseOrder) GetOrderResponse() string {
	if x != nil {
		return x.OrderResponse
	}
	return ""
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05proto\"5\n" +
	"\x0fNewRequestOrder\x12\"\n" +
	"\forderRequest\x18\x01 \x01(\tR\forderRequest\"8\n" +
	"\x10NewResponseOrder\x12$\n" +
	"\rorderResponse\x18\x02 \x01(\tR\rorderResponse2M\n" +
	"\fOrderService\x12=\n" +
	"\bNewOrder\x12\x16.proto.NewRequestOrder\x1a\x17.proto.NewResponseOrder\"\x00B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_order_proto_goTypes = []any{
	(*NewRequestOrder)(nil),  // 0: proto.NewRequestOrder
	(*NewResponseOrder)(nil), // 1: proto.NewResponseOrder
}
var file_order_proto_depIdxs = []int32{
	0, // 0: proto.OrderService.NewOrder:input_type -> proto.NewRequestOrder
	1, // 1: proto.OrderService.NewOrder:output_type -> proto.NewResponseOrder
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
